### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by tonsuke0615** [tonsuke0615/fleamarket_sample_78b#61]
■ URL
IPアドレス：54.249.182.76
Github（最終課題のリポジトリ）：https://github.com/tonsuke0615/fleamarket_sample_78b
■ Basic認証
ID：tonsuke0615
Pass：dai0615

■ テスト用アカウント
◯ 購入者用
メールアドレス：1ample@sample.com
パスワード：11111111

◯ 購入用カード情報
番号：4242424242424242
期限：12/24
セキュリティカード：123

◯ 出品者用
メールアドレス：yuki@yuki
パスワード：kurosuke1222

**Comment by apapa1031** [comment]
ご提出ありがとうございます！
以下の修正点が見受けられたので、修正をお願い致します。

①出品内容に著作物があります。著作物の写真をフリーのものに変えて頂きますようよろしくお願い致します。
<img width="229" alt="スクリーンショット 2020-11-12 20 50 49" src="https://user-images.githubusercontent.com/62538354/98937593-f63cd200-2529-11eb-8148-2c6d32ceb991.png">

**Comment by tonsuke0615** [comment]
ご確認ありがとうございます。ご指摘があった部分を削除しましたのでご確認よろしくお願いいたします。

**Comment by kubota-tec** [comment]
早速の修正、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので追加で修正をお願いします！


**`ユーザー新規登録時`**
ユーザー本名のふりがなが、それぞれ名字と名前で全角入力できる
→こちらが漢字でも登録できる状態です。仮名（平仮名や片仮名）でのみ登録できるよう修正お願いいたします。


`**商品購入時**`
クレジットカードが登録していないと、商品が購入できない。
→こちら、カード登録前でも購入が確認できました。

`**商品一覧**`
画像素材が表示されている。画像がリンク切れなどになっていない
一部画像（牛丼）がリンク切れになっているようです。


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by kaji-yuki** [comment]
上記修正いたしました。
テスト用アカウントは、現時点ではカードを登録していない状態です。
※　出品者用アカウントも、カード情報は未登録です。

**Comment by MakiTaka** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので追加で修正をお願いします！

トップページ、商品詳細ページの金額の単位がありません。（このままだと円なのかドルなのか単位が不明です）

クレジットカードなど他の点は確認いたしましたのでこちらの修正後再提出をよろしくお願いします。


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by tonsuke0615** [comment]
上記修正しました。
トップページ、商品詳細ページの金額の単位を追加しました。
ご確認よろしくお願いします。

**Comment by MakiTaka** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

昨日の段階で著作権フリーの画像に全て変更してくださっているとは思いますが、
もし万が一変更していない場合は、以下のサイトなどから投稿する内容は厳選しておいてください。
https://www.photo-ac.com/

https://www.pakutaso.com/

昨今、コンプライアンスが厳しくなっている影響からこの辺りは厳しくなっていますのでご確認のほどよろしくお願いいたします。

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**
